### ISSUE TITLE
question for meshengine

### ISSUE THREAD

**Issue by withlin** [MeshEngine/meshengine#1]
The meshengine requirements for the kernel version and network card of the operating system?
just like `socket_ops` base ebpf(At least 4.18.x kernel version)?

**Comment by withlin** [comment]
@arikachen @super4hanlin ping

**Comment by super4hanlin** [comment]
For independent mode，requirements for kernel is very loose. But for binding mode,  because of AF_XDP and sockops, 5.4.x kernel version is suggestted.
Regarding as NICs, we mainly tested mellanox and Intel NIC.

**Comment by withlin** [comment]
tks @super4hanlin  /close
